package PA2_G23;

import PA2_G23.Enums.UseCases;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.producer.ProducerConfig;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

public class Util {
    public static <T> T mostCommon(List<T> list) {
        Map<T, Integer> map = new HashMap<>();

        for (T t : list) {
            Integer val = map.get(t);
            map.put(t, val == null ? 1 : val + 1);
        }

        Map.Entry<T, Integer> max = null;

        for (Map.Entry<T, Integer> e : map.entrySet()) {
            if (max == null || e.getValue() > max.getValue())
                max = e;
        }

        return max.getKey();
    }

    public static void configureProducer(UseCases useCase, Properties properties) {
        switch (useCase) {
            case Uc1 -> {
                properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ProducerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ProducerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ProducerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG, "40000");
                properties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.METADATA_MAX_IDLE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.BATCH_SIZE_CONFIG, "16384");
                properties.setProperty(ProducerConfig.ACKS_CONFIG, "all");
                properties.setProperty(ProducerConfig.LINGER_MS_CONFIG, "0");
                properties.setProperty(ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, "1048576");
                properties.setProperty(ProducerConfig.MAX_BLOCK_MS_CONFIG, "60000");
                properties.setProperty(ProducerConfig.BUFFER_MEMORY_CONFIG, "33554432");
                properties.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "none");
                properties.setProperty(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, "5");
                properties.setProperty(ProducerConfig.RETRIES_CONFIG, "0");
                properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
                properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArraySerializer");
                properties.setProperty(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "false");
                properties.setProperty(ProducerConfig.PARTITIONER_CLASS_CONFIG, "PA2_G23.Models.SensorIdPartitioner");
            }
            case Uc2 -> {
                properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ProducerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ProducerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.RETRY_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.METRICS_NUM_SAMPLES_CONFIG, "1");
                properties.setProperty(ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG, "20000");
                properties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.METADATA_MAX_IDLE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.BATCH_SIZE_CONFIG, "16384");
                properties.setProperty(ProducerConfig.ACKS_CONFIG, "1");
                properties.setProperty(ProducerConfig.LINGER_MS_CONFIG, "0");
                properties.setProperty(ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, "1048576");
                properties.setProperty(ProducerConfig.MAX_BLOCK_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.BUFFER_MEMORY_CONFIG, "33554432");
                properties.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "none");
                properties.setProperty(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, "1");
                properties.setProperty(ProducerConfig.RETRIES_CONFIG, "0");
                properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
                properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArraySerializer");
                properties.setProperty(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "false");
                properties.setProperty(ProducerConfig.PARTITIONER_CLASS_CONFIG, "PA2_G23.Models.SensorIdPartitioner");
            }
            case Uc3 -> {
                properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ProducerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ProducerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.METADATA_MAX_IDLE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.BATCH_SIZE_CONFIG, "30000");
                properties.setProperty(ProducerConfig.ACKS_CONFIG, "all");
                properties.setProperty(ProducerConfig.LINGER_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, "1048576");
                properties.setProperty(ProducerConfig.MAX_BLOCK_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.BUFFER_MEMORY_CONFIG, "33554432");
                properties.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "none");
                properties.setProperty(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, "5");
                properties.setProperty(ProducerConfig.RETRIES_CONFIG, "3");
                properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
                properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArraySerializer");
                properties.setProperty(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "false");
                properties.setProperty(ProducerConfig.PARTITIONER_CLASS_CONFIG, "PA2_G23.Models.SensorIdPartitioner");
            }
            case Uc4 -> {
                properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ProducerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ProducerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG, "50000");
                properties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.METADATA_MAX_IDLE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.BATCH_SIZE_CONFIG, "30000");
                properties.setProperty(ProducerConfig.ACKS_CONFIG, "all");
                properties.setProperty(ProducerConfig.LINGER_MS_CONFIG, "200");
                properties.setProperty(ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, "1048576");
                properties.setProperty(ProducerConfig.MAX_BLOCK_MS_CONFIG, "60000");
                properties.setProperty(ProducerConfig.BUFFER_MEMORY_CONFIG, "33554432");
                properties.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "none");
                properties.setProperty(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, "1");
                properties.setProperty(ProducerConfig.RETRIES_CONFIG, "6");
                properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
                properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArraySerializer");
                properties.setProperty(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "false");
                properties.setProperty(ProducerConfig.PARTITIONER_CLASS_CONFIG, "PA2_G23.Models.SensorIdPartitioner");
            }
            case Uc5 -> {
                properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ProducerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ProducerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG, "40000");
                properties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.METADATA_MAX_IDLE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.BATCH_SIZE_CONFIG, "16384");
                properties.setProperty(ProducerConfig.ACKS_CONFIG, "all");
                properties.setProperty(ProducerConfig.LINGER_MS_CONFIG, "0");
                properties.setProperty(ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, "1048576");
                properties.setProperty(ProducerConfig.MAX_BLOCK_MS_CONFIG, "60000");
                properties.setProperty(ProducerConfig.BUFFER_MEMORY_CONFIG, "33554432");
                properties.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "none");
                properties.setProperty(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, "5");
                properties.setProperty(ProducerConfig.RETRIES_CONFIG, "0");
                properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
                properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArraySerializer");
                properties.setProperty(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "false");
                properties.setProperty(ProducerConfig.PARTITIONER_CLASS_CONFIG, "PA2_G23.Models.SensorIdPartitioner");
            }
            case Uc6 -> {
                properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ProducerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ProducerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ProducerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ProducerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG, "40000");
                properties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ProducerConfig.METADATA_MAX_IDLE_CONFIG, "300000");
                properties.setProperty(ProducerConfig.BATCH_SIZE_CONFIG, "16384");
                properties.setProperty(ProducerConfig.ACKS_CONFIG, "all");
                properties.setProperty(ProducerConfig.LINGER_MS_CONFIG, "0");
                properties.setProperty(ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG, "120000");
                properties.setProperty(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, "1048576");
                properties.setProperty(ProducerConfig.MAX_BLOCK_MS_CONFIG, "60000");
                properties.setProperty(ProducerConfig.BUFFER_MEMORY_CONFIG, "33554432");
                properties.setProperty(ProducerConfig.COMPRESSION_TYPE_CONFIG, "none");
                properties.setProperty(ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION, "5");
                properties.setProperty(ProducerConfig.RETRIES_CONFIG, "0");
                properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
                properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArraySerializer");
                properties.setProperty(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "false");
                properties.setProperty(ProducerConfig.PARTITIONER_CLASS_CONFIG, "PA2_G23.Models.SensorIdPartitioner");
            }
        }
    }

    public static void configureConsumer(UseCases useCase, Properties properties) {
        switch (useCase) {
            case Uc1:
                properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
                properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArrayDeserializer");
                properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, "1");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "1");
                properties.setProperty(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "null");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "500");
                properties.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "45000");
                properties.setProperty(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, "14000");
                properties.setProperty(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
                properties.setProperty(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "5000");
                properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
                properties.setProperty(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, "52428800");
                properties.setProperty(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, "500");
                properties.setProperty(ConsumerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "1048576");
                properties.setProperty(ConsumerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ConsumerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ConsumerConfig.CLIENT_RACK_CONFIG, "");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.CHECK_CRCS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG, "40000");
                properties.setProperty(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.ISOLATION_LEVEL_CONFIG, "read_uncommitted");
                properties.setProperty(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SECURITY_PROVIDERS_CONFIG, "null");
                break;
            case Uc2:
                properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
                properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArrayDeserializer");
                properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, "1");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "1");
                properties.setProperty(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "null");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "10");
                properties.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, "2900");
                properties.setProperty(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
                properties.setProperty(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "5000");
                properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
                properties.setProperty(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, "52428800");
                properties.setProperty(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "1048576");
                properties.setProperty(ConsumerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ConsumerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ConsumerConfig.CLIENT_RACK_CONFIG, "");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG, "1");
                properties.setProperty(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.CHECK_CRCS_CONFIG, "false");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG, "20000");
                properties.setProperty(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.ISOLATION_LEVEL_CONFIG, "read_uncommitted");
                properties.setProperty(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SECURITY_PROVIDERS_CONFIG, "null");
                break;
            case Uc3:
                properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
                properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArrayDeserializer");
                properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, "600");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "20");
                properties.setProperty(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "null");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "150000");
                properties.setProperty(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "45000");
                properties.setProperty(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, "14000");
                properties.setProperty(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
                properties.setProperty(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "2000");
                properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
                properties.setProperty(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, "52428800");
                properties.setProperty(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, "20000");
                properties.setProperty(ConsumerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "1048576");
                properties.setProperty(ConsumerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ConsumerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ConsumerConfig.CLIENT_RACK_CONFIG, "");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.CHECK_CRCS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.ISOLATION_LEVEL_CONFIG, "read_uncommitted");
                properties.setProperty(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SECURITY_PROVIDERS_CONFIG, "null");
                break;
            case Uc4:
                properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
                properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArrayDeserializer");
                properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, "1");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "1");
                properties.setProperty(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "null");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "200");
                properties.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, "90000");
                properties.setProperty(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
                properties.setProperty(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
                properties.setProperty(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, "52428800");
                properties.setProperty(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, "20000");
                properties.setProperty(ConsumerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "1048576");
                properties.setProperty(ConsumerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ConsumerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ConsumerConfig.CLIENT_RACK_CONFIG, "");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.CHECK_CRCS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG, "50000");
                properties.setProperty(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.ISOLATION_LEVEL_CONFIG, "read_uncommitted");
                properties.setProperty(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SECURITY_PROVIDERS_CONFIG, "null");
                break;
            case Uc5:
                properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
                properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArrayDeserializer");
                properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, "1");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "1");
                properties.setProperty(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "null");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "200");
                properties.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "45000");
                properties.setProperty(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, "14000");
                properties.setProperty(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
                properties.setProperty(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "5000");
                properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
                properties.setProperty(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, "52428800");
                properties.setProperty(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, "500");
                properties.setProperty(ConsumerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "1048576");
                properties.setProperty(ConsumerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ConsumerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ConsumerConfig.CLIENT_RACK_CONFIG, "");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.CHECK_CRCS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG, "40000");
                properties.setProperty(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.ISOLATION_LEVEL_CONFIG, "read_uncommitted");
                properties.setProperty(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SECURITY_PROVIDERS_CONFIG, "null");
                break;
            case Uc6:
                properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
                properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.ByteArrayDeserializer");
                properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
                properties.setProperty(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, "1");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "1");
                properties.setProperty(ConsumerConfig.GROUP_INSTANCE_ID_CONFIG, "null");
                properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "500");
                properties.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "45000");
                properties.setProperty(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, "14000");
                properties.setProperty(ConsumerConfig.CLIENT_DNS_LOOKUP_CONFIG, "use_all_dns_ips");
                properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
                properties.setProperty(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "5000");
                properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
                properties.setProperty(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, "52428800");
                properties.setProperty(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, "500");
                properties.setProperty(ConsumerConfig.METADATA_MAX_AGE_CONFIG, "300000");
                properties.setProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "1048576");
                properties.setProperty(ConsumerConfig.SEND_BUFFER_CONFIG, "131072");
                properties.setProperty(ConsumerConfig.RECEIVE_BUFFER_CONFIG, "32768");
                properties.setProperty(ConsumerConfig.CLIENT_ID_CONFIG, "");
                properties.setProperty(ConsumerConfig.CLIENT_RACK_CONFIG, "");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, "50");
                properties.setProperty(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, "1000");
                properties.setProperty(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, "100");
                properties.setProperty(ConsumerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.METRICS_NUM_SAMPLES_CONFIG, "2");
                properties.setProperty(ConsumerConfig.METRICS_RECORDING_LEVEL_CONFIG, "INFO");
                properties.setProperty(ConsumerConfig.METRIC_REPORTER_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.CHECK_CRCS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG, "10000");
                properties.setProperty(ConsumerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG, "30000");
                properties.setProperty(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, "540000");
                properties.setProperty(ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG, "40000");
                properties.setProperty(ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG, "60000");
                properties.setProperty(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, "");
                properties.setProperty(ConsumerConfig.EXCLUDE_INTERNAL_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.ISOLATION_LEVEL_CONFIG, "read_uncommitted");
                properties.setProperty(ConsumerConfig.ALLOW_AUTO_CREATE_TOPICS_CONFIG, "true");
                properties.setProperty(ConsumerConfig.SECURITY_PROVIDERS_CONFIG, "null");
                break;
        }
    }
}
